homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/ttyUSB0
frontend: true
advanced:
  log_output:
    - console
# mettre 675X ou X est le numéro du groupe
  pan_id: 6753
# choisir un canal entre 11 et 26.
  channel: 13
device_options:
  legacy: false
passlist:
  - '0xa4c138de63548d15'
  - '0x90fd9ffffe14c33d'
  - '0xd0cf5efffe18cb8c'
devices: {}

