homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/ttyUSB0
frontend: true
advanced:
  log_output:
    - console
# mettre 675X ou X est le numéro du groupe
  pan_id: 6753
device_options:
  legacy: false
blocklist:
  - '0xa4c138c35298bc87'
  - '0xa4c138a82a64f6f2'
  - '0xa4c1381520886a8c'
  - '0xa4c138fcfcd1ab05'
  - '0xd0cf5efffe18cb8c'
  - '0xa4c1389c73550ed1'
  - '0x90fd9ffffe193cfc'
devices: {}
